### ISSUE TITLE
Tabbing Quirks

### ISSUE THREAD

**Issue by bramus** [GoogleChromeLabs/designcember#30]
I noticed some weird behavior when tabbing:

https://user-images.githubusercontent.com/213073/145047420-ed80e555-381a-40d1-93d9-b87cc83a65cb.mp4

1. When the focus first hits day 1, it does nothing. The hash of the page also doesn't change. Once I hit day 2, it works.
1. When hitting day 3, the page will first move the tooltip and then scroll the day into view.

For that 2nd part, I think that flipping around the order of those actions would fix it: first scroll the day into view, and only then reposition the tooltip.

**Comment by argyleink** [comment]
thanks Bramus! i'm doing some refactors of the tab focus flow today, i'll make sure this is resolved as well 👍🏻

**Comment by bramus** [comment]
I like what you did there; Thanks!
