### ISSUE TITLE
Weird click behavior

### ISSUE THREAD

**Issue by bramus** [GoogleChromeLabs/designcember#7]
_(I seem to have stumbled upon the designcember WIP website and code by accident (🤐). Apologies for intervening while y'all are still working on it.)_

I noticed that the click behavior is pretty weird. I expected clicking the boxes to act as a toggle: click once to show the popover, click again to hide it.

This is not the case, leading me to click around wildly in order to hide the popover. See this recording:

https://user-images.githubusercontent.com/213073/144096562-52465275-0338-4c41-a9ee-714bb898db75.mp4

Once the popover gets hidden (by clicking outside) a JS TypeError is triggered too, and there's no way to re-show the popover.

![image](https://user-images.githubusercontent.com/213073/144096998-b520aee8-a81e-4be4-93f0-1748140c0d40.png)

**Comment by argyleink** [comment]
fixed
